services:
  elasticsearch:
    build:
      context: '.'
      dockerfile: 'Dockerfile.elasticsearch'
      args:
        ES_VERSION: '8.13.0'
      secrets:
        - nugetconfig
    cpus: 1
    mem_limit: '1G'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true -Xlog:disable'
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
  kibana:
    image: 'kibana:8.13.0'
    depends_on:
      elasticsearch:
        condition: 'service_healthy'
    ports:
      - '5601:5601'
    volumes:
      - './kibana.yml:/usr/share/kibana/config/kibana.yml'
    healthcheck:
      test: 'curl -f localhost:5601/api/status || exit 1'
      start_period: '60s'
      start_interval: '1s'
  kibana-init:
    image: 'kibana:8.13.0'
    restart: 'no'
    depends_on:
      kibana:
        condition: 'service_healthy'
    entrypoint:
    command: >
      curl -fsS kibana:5601/api/data_views/data_view
        -H 'Content-Type: application/json'
        -H 'kbn-xsrf: blah'
        -d '{"data_view":{"title":"quotes","name":"quotes"},"override":true}'
        -o /dev/null

secrets:
  nugetconfig:
    file: /mnt/c/Users/max/AppData/Roaming/NuGet/NuGet.Config
