services:
  elasticsearch:
    build:
      context: '.'
      dockerfile: 'docker/elasticsearch.Dockerfile'
      args:
        ES_VERSION: '8.17.0'
      secrets:
        - 'nugetconfig'
    cpus: 1
    mem_limit: '1G'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
  elasticsearch-arm64:
    extends:
      service: 'elasticsearch'
    profiles:
      - 'prod'
    build:
      platforms:
        # Not building a multi-platform image so that the ARM image can be pushed separately due to its large size
        - 'linux/arm64'
  kibana:
    image: 'kibana:8.17.0'
    depends_on:
      elasticsearch:
        condition: 'service_healthy'
    ports:
      - '5601:5601'
    volumes:
      - './kibana.yml:/usr/share/kibana/config/kibana.yml'
    healthcheck:
      test: 'curl -f localhost:5601/api/status || exit 1'
      start_period: '60s'
      start_interval: '1s'
  kibana-init:
    image: 'kibana:8.17.0'
    restart: 'no'
    depends_on:
      kibana:
        condition: 'service_healthy'
    entrypoint: ''
    command: >
      curl -fsS kibana:5601/api/data_views/data_view
        -H 'Content-Type: application/json'
        -H 'kbn-xsrf: blah'
        -d '{"data_view":{"title":"quotes","name":"quotes"},"override":true}'
        -o /dev/null &&
      curl -fsS -X PUT 'elasticsearch:9200/.*/_settings'
        -H 'Content-Type: application/json'
        -d '{"index":{"number_of_replicas":0}}'
  sqlarserver:
    image: 'kagamine/sqlarserver'
    command: 'Serifu.db'
    ports:
      - '3939:80'
    volumes:
      - '.:/srv:ro'
  web:
    profiles:
      - 'preview'
    build:
      context: '.'
      dockerfile: 'docker/web.Dockerfile'
      secrets:
        - 'nugetconfig'
    depends_on:
      elasticsearch:
        condition: 'service_healthy'
      sqlarserver:
        condition: 'service_healthy'
    ports:
      - '3900:3900'
    environment:
      AudioFileBaseUrl: 'http://localhost:3939'
  web-arm64:
    extends:
      service: 'web'
    profiles:
      - 'prod'
    build:
      platforms:
        - 'linux/arm64'
  s3mock:
    profiles:
      - 's3mock'
    image: 'adobe/s3mock'
    cpus: 1
    mem_limit: '512M'
    ports:
      - '9090:9090'
    volumes:
      - './_stuff/s3mock-data:/data'
    environment:
      initialBuckets: 'mock-audio-bucket'
      root: '/data'
      retainFilesOnExit: 'true'

secrets:
  nugetconfig:
    file: '/mnt/c/Users/max/AppData/Roaming/NuGet/NuGet.Config'
