services:
  elasticsearch:
    build:
      context: '.'
      dockerfile: 'Dockerfile.elasticsearch'
    cpus: 1
    mem_limit: '1G'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true -Xlog:disable'
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
